[supervisord]

nodaemon=true
user=root

logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid


; ============================================================
; Apache
; ============================================================

[program:apache]

command=/usr/sbin/apache2ctl -D FOREGROUND

autostart=true
autorestart=true

priority=10

stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0


; ============================================================
; Laravel Scheduler
; ============================================================

[program:schedule-worker]

command=php /var/www/html/artisan schedule:work

directory=/var/www/html

autostart=true
autorestart=true

user=www-data

priority=20

stdout_logfile=/var/www/html/storage/logs/schedule_worker.log
stdout_logfile_maxbytes=0

stderr_logfile=/var/www/html/storage/logs/schedule_worker_error.log
stderr_logfile_maxbytes=0